require 'user.plugins'
require 'user.options'
require 'user.trailing_whitespaces'
require 'user.nvim-tree'
require 'user.colorscheme'
require 'user.keymaps'
require 'user.treesitter'

 -- require 'user.cmp'
 -- require 'user.lsp'
