#!/bin/sh

## BSPWM
# Desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Floating rules
bspc rule -a Timer state=floating
bspc rule -a "Kengine" state=floating
bspc rule -a "No Title Yet" state=floating

## Hotkeys
# Start hotkey daemon
if ! pgrep --exact "sxhkd" > /dev/null ; then
  sxhkd &
fi

## VISUAL
# Input Methods
fcitx >/dev/null 2>&1

# Set background
~/.fehbg

# Compositor
if ! pgrep --exact "picom" > /dev/null ; then
  picom &
fi

# Panel
if ! pgrep --exact "polybar" > /dev/null; then
  polybar bspwm > /tmp/polybar.bspwm.log 2>&1 &
fi
