#!/bin/sh
mod="Mod4"

#########
# Basic #
#########
riverctl map normal $mod+Shift E exit
riverctl background-color       0x002b36
riverctl border-color-focused   0x93a1a1
riverctl border-color-unfocused 0x586e75
riverctl set-repeat 50 300

########
# View #
########
riverctl map normal $mod Q close

riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

riverctl map-pointer normal $mod BTN_LEFT  move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

##########
# Window #
##########
riverctl map normal $mod Space toggle-float
riverctl map normal $mod F toggle-fullscreen

##########
# Layout #
##########
riverctl default-layout rivertile

riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

#######
# Tag #
#######
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal $mod               $i set-focused-tags    $tags
    riverctl map normal $mod+Shift         $i set-view-tags       $tags
    riverctl map normal $mod+Control       $i toggle-focused-tags $tags
    riverctl map normal $mod+Shift+Control $i toggle-view-tags    $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal $mod       0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags    $all_tags

######################
# Spawn Applications #
######################
riverctl map normal $mod+Shift Return spawn 'bemenu-run'
riverctl map normal $mod       Return spawn 'foot'
riverctl map normal $mod+Shift S      spawn 'grim -g "$(slurp)"'

riverctl map normal $mod       R spawn 'yinput-interactive-record-begin'
riverctl map normal $mod+Shift R spawn 'yinput-interactive-record-end'
riverctl map normal $mod       P spawn 'yinput-interactive-replay'

###########
# Startup #
###########
rivertile -view-padding 6 -outer-padding 6 &

waybar      &
dunst       &
fcitx5      &

pipewire    &
sleep 1
wireplumber &

wait
